/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pradip_kumar' at '3/25/16 2:35 AM' with Gradle 2.12
 *
 * @author pradip_kumar, @date 3/25/16 2:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
